import { Platform, StatusBar, StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
  flex: 1,
  paddingTop: Platform.OS === "android" ? (StatusBar.currentHeight ?? 0) : 0,
  backgroundColor: "#F6F3EC",
},
  container: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 40 },
  resultContainer: { flexGrow: 1, justifyContent: "center", paddingHorizontal: 24, paddingVertical: 40 },
  eyebrow: { fontSize: 13, fontWeight: "700", letterSpacing: 1.2, textTransform: "uppercase", color: "#9A3D3D" },
  heroTitle: { marginTop: 8, fontSize: 38, lineHeight: 44, fontWeight: "900", color: "#1C1A18" },
  title: { marginTop: 8, fontSize: 34, lineHeight: 40, fontWeight: "800", color: "#1C1A18" },
  description: { marginTop: 10, fontSize: 16, lineHeight: 23, color: "#5D5852" },
  todayCard: { marginTop: 28, padding: 20, borderRadius: 22, backgroundColor: "#26211D" },
  todayHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  todaySectionTitle: { fontSize: 20, fontWeight: "800", color: "#FFFFFF" },
  todayTitle: { marginTop: 16, fontSize: 28, fontWeight: "900", color: "#FFFFFF" },
  todayBody: { marginTop: 10, fontSize: 16, lineHeight: 23, color: "#D9D2C9" },
  timeBadge: { paddingHorizontal: 10, paddingVertical: 5, borderRadius: 99, fontSize: 13, fontWeight: "800", color: "#2D2824", backgroundColor: "#F2D9A2" },
  reviewCard: { marginTop: 16, padding: 18, borderRadius: 20, borderWidth: 1, borderColor: "#D7C9B8", backgroundColor: "#FFF9ED" },
  reviewHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  reviewEyebrow: { fontSize: 12, fontWeight: "900", letterSpacing: 1, textTransform: "uppercase", color: "#9A3D3D" },
  reviewTitle: { marginTop: 5, fontSize: 21, fontWeight: "900", color: "#1C1A18" },
  reviewCountBadge: { minWidth: 46, height: 46, alignItems: "center", justifyContent: "center", borderRadius: 15, backgroundColor: "#F0E2DE" },
  reviewCount: { fontSize: 20, fontWeight: "900", color: "#9A3D3D" },
  reviewBody: { marginTop: 12, fontSize: 15, lineHeight: 21, color: "#5D5852" },
  reviewHistory: { marginTop: 7, fontSize: 13, fontWeight: "700", color: "#80766B" },
  reviewButton: { alignItems: "center", marginTop: 14, paddingVertical: 13, borderRadius: 14, backgroundColor: "#302822" },
  reviewButtonText: { fontSize: 15, fontWeight: "900", color: "#FFFFFF" },
  courseHeading: { marginTop: 30 },
  unitCard: { marginTop: 12, padding: 18, borderRadius: 20, borderWidth: 1, borderColor: "#E5DED4", backgroundColor: "#FFFFFF" },
  unitHeader: { flexDirection: "row", justifyContent: "space-between" },
  unitLevel: { fontSize: 13, fontWeight: "900", color: "#9A3D3D" },
  unitCount: { fontSize: 13, fontWeight: "700", color: "#746D65" },
  unitTitle: { marginTop: 10, fontSize: 23, fontWeight: "900", color: "#1C1A18" },
  lessonRow: { flexDirection: "row", alignItems: "center", marginTop: 18, paddingTop: 16, borderTopWidth: 1, borderTopColor: "#EEE8DF" },
  lessonNumber: { width: 42, height: 42, alignItems: "center", justifyContent: "center", borderRadius: 14, backgroundColor: "#F0E2DE" },
  lessonNumberCompleted: { backgroundColor: "#E4F2E8" },
  lessonNumberText: { fontSize: 17, fontWeight: "900", color: "#9A3D3D" },
  lessonInfo: { flex: 1, marginLeft: 13 },
  lessonTitle: { fontSize: 17, fontWeight: "800", color: "#1C1A18" },
  lessonMeta: { marginTop: 3, fontSize: 13, color: "#746D65" },
  lessonChevron: { marginLeft: 8, fontSize: 28, color: "#A39A90" },
  backLink: { alignSelf: "flex-start", marginBottom: 18, paddingVertical: 4 },
  backLinkText: { fontSize: 15, fontWeight: "800", color: "#9A3D3D" },
  stageRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 24 },
  stageItem: { flex: 1, alignItems: "center" },
  stageDot: { width: 9, height: 9, borderRadius: 99 },
  stageDotActive: { backgroundColor: "#B54444" },
  stageDotInactive: { backgroundColor: "#D8D0C6" },
  stageLabel: { marginTop: 6, fontSize: 11, color: "#8A8279" },
  stageLabelActive: { fontWeight: "800", color: "#433D37" },
  section: { marginTop: 28 },
  sectionTitle: { fontSize: 20, fontWeight: "800", color: "#1C1A18" },
  card: { marginTop: 12, padding: 18, borderRadius: 18, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5DED4" },
  audioHeaderRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
  soundButton: { width: 42, height: 42, marginLeft: 12, alignItems: "center", justifyContent: "center", borderRadius: 13, backgroundColor: "#F0E2DE" },
  soundButtonText: { fontSize: 19 },
  japaneseTitle: { flexShrink: 1, fontSize: 24, fontWeight: "800", color: "#1C1A18" },
  meaning: { marginTop: 4, fontSize: 14, fontWeight: "700", color: "#9A3D3D" },
  body: { marginTop: 10, fontSize: 16, lineHeight: 23, color: "#5D5852" },
  formula: { marginTop: 14, padding: 12, borderRadius: 12, fontSize: 16, fontWeight: "700", color: "#25211E", backgroundColor: "#F0ECE5" },
  caution: { marginTop: 10, fontSize: 14, lineHeight: 20, color: "#795A25" },
  wordRow: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", marginTop: 10, padding: 16, borderRadius: 16, backgroundColor: "#FFFFFF", borderWidth: 1, borderColor: "#E5DED4" },
  wordTextBlock: { flexShrink: 1 },
  wordWritten: { fontSize: 29, fontWeight: "800", color: "#1C1A18" },
  wordReading: { marginTop: 2, fontSize: 14, color: "#746D65" },
  wordActions: { flex: 1, marginLeft: 12, alignItems: "flex-end" },
  wordMeaning: { flexShrink: 1, fontSize: 16, fontWeight: "700", textAlign: "right", color: "#443F3A" },
  exampleJapanese: { flexShrink: 1, fontSize: 25, fontWeight: "800", color: "#1C1A18" },
  exampleReading: { marginTop: 5, fontSize: 14, color: "#746D65" },
  exampleTranslation: { marginTop: 12, fontSize: 16, fontWeight: "700", color: "#9A3D3D" },
  navigation: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 24 },
  secondaryButton: { minWidth: 100, alignItems: "center", paddingHorizontal: 18, paddingVertical: 13, borderRadius: 14, borderWidth: 1, borderColor: "#CFC7BC", backgroundColor: "#FFFFFF" },
  secondaryWideButton: { alignItems: "center", marginTop: 12, paddingVertical: 14, borderRadius: 14, borderWidth: 1, borderColor: "#CFC7BC", backgroundColor: "#FFFFFF" },
  secondaryButtonText: { fontSize: 16, fontWeight: "800", color: "#38332E" },
  disabledButton: { opacity: 0.35 },
  primaryButton: { alignItems: "center", marginTop: 16, paddingVertical: 14, borderRadius: 14, backgroundColor: "#B54444" },
  primaryButtonSmall: { minWidth: 120, alignItems: "center", paddingHorizontal: 20, paddingVertical: 14, borderRadius: 14, backgroundColor: "#B54444" },
  primaryButtonText: { fontSize: 16, fontWeight: "800", color: "#FFFFFF" },
  practiceHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  exerciseCounter: { fontSize: 14, fontWeight: "800", color: "#9A3D3D" },
  prompt: { fontSize: 19, lineHeight: 26, fontWeight: "800", color: "#1C1A18" },
  choiceList: { marginTop: 16 },
  choiceButton: { alignItems: "center", marginTop: 9, paddingVertical: 15, borderRadius: 14, borderWidth: 1, borderColor: "#D6CEC3", backgroundColor: "#FCFBF8" },
  choiceButtonSelected: { borderColor: "#B54444", backgroundColor: "#F6E8E5" },
  choiceText: { fontSize: 22, fontWeight: "800", color: "#28231F" },
  builderAnswer: { minHeight: 74, flexDirection: "row", flexWrap: "wrap", alignItems: "center", marginTop: 16, padding: 10, borderRadius: 14, borderWidth: 1, borderColor: "#D6CEC3", backgroundColor: "#FCFBF8" },
  builderPlaceholder: { fontSize: 14, color: "#8A8279" },
  selectedToken: { margin: 4, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 10, backgroundColor: "#B54444" },
  selectedTokenText: { fontSize: 18, fontWeight: "800", color: "#FFFFFF" },
  tokenList: { flexDirection: "row", flexWrap: "wrap", marginTop: 12 },
  tokenButton: { marginRight: 8, marginBottom: 8, paddingHorizontal: 14, paddingVertical: 10, borderRadius: 11, backgroundColor: "#EEE8DF" },
  tokenButtonText: { fontSize: 18, fontWeight: "800", color: "#302B27" },
  clearButton: { alignSelf: "flex-start", paddingVertical: 5 },
  clearButtonText: { fontSize: 14, fontWeight: "700", color: "#9A3D3D" },
  input: { marginTop: 18, paddingHorizontal: 15, paddingVertical: 14, borderWidth: 1, borderColor: "#CFC7BC", borderRadius: 14, fontSize: 18, backgroundColor: "#FCFBF8", color: "#1C1A18" },
  feedback: { marginTop: 14, padding: 14, borderRadius: 14 },
  feedbackCorrect: { backgroundColor: "#E4F2E8" },
  feedbackIncorrect: { backgroundColor: "#F7E2E0" },
  feedbackText: { fontSize: 16, fontWeight: "800", color: "#2C2824" },
  feedbackExplanation: { marginTop: 6, fontSize: 14, lineHeight: 20, color: "#514B45" },
  correctAnswer: { marginTop: 8, fontSize: 15, fontWeight: "800", color: "#7A302D" },
  listenAnswerButton: { alignSelf: "flex-start", marginTop: 12, paddingHorizontal: 12, paddingVertical: 9, borderRadius: 11, backgroundColor: "#FFFFFF" },
  listenAnswerText: { fontSize: 14, fontWeight: "800", color: "#453D36" },
  resultEmoji: { fontSize: 24, fontWeight: "900", textAlign: "center", color: "#9A3D3D" },
  resultTitle: { marginTop: 12, fontSize: 35, fontWeight: "900", textAlign: "center", color: "#1C1A18" },
  resultPercent: { marginTop: 18, fontSize: 68, fontWeight: "900", textAlign: "center", color: "#B54444" },
  resultSummary: { marginTop: 4, fontSize: 17, textAlign: "center", color: "#5D5852" },
  resultCard: { marginTop: 28, padding: 18, borderRadius: 18, backgroundColor: "#FFFFFF" },
  resultCardTitle: { fontSize: 18, fontWeight: "900", color: "#1C1A18" },
  resultLine: { marginTop: 9, fontSize: 15, lineHeight: 21, color: "#514B45" },
  reviewScheduledText: { marginTop: 16, fontSize: 14, lineHeight: 20, textAlign: "center", color: "#746D65" },
  linkButton: { alignItems: "center", marginTop: 14, paddingVertical: 10 },
  linkButtonText: { fontSize: 15, fontWeight: "800", color: "#9A3D3D" },
});
