import { StyleSheet } from "react-native";

export const kanaStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F6F3EC" },
  container: { paddingHorizontal: 20, paddingTop: 24, paddingBottom: 48 },
  centeredContainer: {
    flexGrow: 1,
    justifyContent: "center",
    paddingHorizontal: 22,
    paddingVertical: 36,
  },
  eyebrow: {
    fontSize: 13,
    fontWeight: "800",
    letterSpacing: 1.1,
    textTransform: "uppercase",
    color: "#9A3D3D",
  },
  title: { marginTop: 8, fontSize: 36, lineHeight: 42, fontWeight: "900", color: "#1C1A18" },
  description: { marginTop: 10, fontSize: 16, lineHeight: 23, color: "#5D5852" },
  optionCard: {
    marginTop: 12,
    padding: 18,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#DDD4C8",
    backgroundColor: "#FFFFFF",
  },
  optionCardSelected: { borderWidth: 2, borderColor: "#B54444", backgroundColor: "#F8E9E6" },
  optionTitle: { fontSize: 19, fontWeight: "900", color: "#1C1A18" },
  optionBody: { marginTop: 5, fontSize: 14, lineHeight: 20, color: "#665F57" },
  primaryButton: {
    alignItems: "center",
    marginTop: 18,
    paddingVertical: 15,
    borderRadius: 14,
    backgroundColor: "#B54444",
  },
  primaryButtonText: { fontSize: 16, fontWeight: "900", color: "#FFFFFF" },
  secondaryButton: {
    alignItems: "center",
    marginTop: 12,
    paddingVertical: 14,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#CFC7BC",
    backgroundColor: "#FFFFFF",
  },
  secondaryButtonText: { fontSize: 15, fontWeight: "800", color: "#38332E" },
  backButton: { alignSelf: "flex-start", marginBottom: 16, paddingVertical: 5 },
  backButtonText: { fontSize: 15, fontWeight: "800", color: "#9A3D3D" },
  heroCard: { marginTop: 22, padding: 20, borderRadius: 22, backgroundColor: "#26211D" },
  heroKana: { fontSize: 54, fontWeight: "900", color: "#FFFFFF" },
  heroTitle: { marginTop: 6, fontSize: 25, fontWeight: "900", color: "#FFFFFF" },
  heroBody: { marginTop: 8, fontSize: 15, lineHeight: 21, color: "#D9D2C9" },
  progressRow: { flexDirection: "row", justifyContent: "space-between", marginTop: 18 },
  progressLabel: { fontSize: 13, fontWeight: "800", color: "#D9D2C9" },
  progressValue: { fontSize: 13, fontWeight: "900", color: "#F2D9A2" },
  progressTrack: { height: 9, marginTop: 8, borderRadius: 99, backgroundColor: "#4A423B", overflow: "hidden" },
  progressFill: { height: "100%", borderRadius: 99, backgroundColor: "#F2D9A2" },
  sectionTitle: { marginTop: 28, fontSize: 21, fontWeight: "900", color: "#1C1A18" },
  skillCard: {
    marginTop: 11,
    padding: 17,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E3DBD0",
    backgroundColor: "#FFFFFF",
  },
  skillHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  skillTitle: { fontSize: 18, fontWeight: "900", color: "#1C1A18" },
  skillPercent: { fontSize: 16, fontWeight: "900", color: "#9A3D3D" },
  skillBody: { marginTop: 5, fontSize: 14, lineHeight: 20, color: "#665F57" },
  chartRow: { marginTop: 18 },
  chartRowTitle: { marginBottom: 8, fontSize: 14, fontWeight: "900", color: "#776E65" },
  chartGrid: { flexDirection: "row", flexWrap: "wrap" },
  kanaCell: {
    width: 62,
    minHeight: 72,
    alignItems: "center",
    justifyContent: "center",
    marginRight: 8,
    marginBottom: 8,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#E1D8CD",
    backgroundColor: "#FFFFFF",
  },
  kanaCellKnown: { backgroundColor: "#E9F3EB", borderColor: "#C7DDCC" },
  kanaGlyph: { fontSize: 29, fontWeight: "800", color: "#1C1A18" },
  kanaRomaji: { marginTop: 2, fontSize: 12, fontWeight: "700", color: "#746D65" },
  questionCard: {
    marginTop: 24,
    padding: 20,
    borderRadius: 22,
    borderWidth: 1,
    borderColor: "#E1D8CD",
    backgroundColor: "#FFFFFF",
  },
  counter: { fontSize: 13, fontWeight: "900", color: "#9A3D3D" },
  questionPrompt: { marginTop: 14, fontSize: 23, lineHeight: 30, fontWeight: "900", color: "#1C1A18" },
  listeningButton: {
    width: 92,
    height: 92,
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 24,
    borderRadius: 30,
    backgroundColor: "#F0E2DE",
  },
  listeningIcon: { fontSize: 38 },
  optionGrid: { flexDirection: "row", flexWrap: "wrap", justifyContent: "space-between", marginTop: 18 },
  answerOption: {
    width: "48%",
    alignItems: "center",
    marginBottom: 10,
    paddingVertical: 17,
    borderRadius: 15,
    borderWidth: 1,
    borderColor: "#D6CEC3",
    backgroundColor: "#FCFBF8",
  },
  answerOptionSelected: { borderColor: "#B54444", backgroundColor: "#F6E8E5" },
  answerOptionText: { fontSize: 27, fontWeight: "900", color: "#28231F" },
  input: {
    marginTop: 20,
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderWidth: 1,
    borderColor: "#CFC7BC",
    borderRadius: 14,
    fontSize: 21,
    textAlign: "center",
    backgroundColor: "#FCFBF8",
    color: "#1C1A18",
  },
  feedback: { marginTop: 16, padding: 14, borderRadius: 14 },
  feedbackCorrect: { backgroundColor: "#E4F2E8" },
  feedbackIncorrect: { backgroundColor: "#F7E2E0" },
  feedbackText: { fontSize: 16, fontWeight: "900", color: "#2C2824" },
  feedbackAnswer: { marginTop: 5, fontSize: 14, color: "#514B45" },
  resultPercent: { marginTop: 20, fontSize: 70, fontWeight: "900", textAlign: "center", color: "#B54444" },
  resultTitle: { marginTop: 8, fontSize: 31, fontWeight: "900", textAlign: "center", color: "#1C1A18" },
  resultBody: { marginTop: 10, fontSize: 16, lineHeight: 23, textAlign: "center", color: "#5D5852" },
  loadingText: { fontSize: 16, fontWeight: "700", textAlign: "center", color: "#665F57" },
  courseKanaCard: {
    marginTop: 16,
    padding: 18,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#D8D1E2",
    backgroundColor: "#F6F1FB",
  },
  courseKanaHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  courseKanaGlyph: { fontSize: 36, fontWeight: "900", color: "#5B3A70" },
  courseKanaTitle: { fontSize: 21, fontWeight: "900", color: "#1C1A18" },
  courseKanaBody: { marginTop: 8, fontSize: 15, lineHeight: 21, color: "#5D5852" },
});
