import { StyleSheet } from "react-native";

export const numberStyles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#F6F3EC" },
  container: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 44 },
  backButton: { alignSelf: "flex-start", marginBottom: 18, paddingVertical: 5 },
  backButtonText: { fontSize: 15, fontWeight: "800", color: "#9A3D3D" },
  eyebrow: { fontSize: 13, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase", color: "#9A3D3D" },
  title: { marginTop: 8, fontSize: 35, lineHeight: 41, fontWeight: "900", color: "#1C1A18" },
  description: { marginTop: 10, fontSize: 16, lineHeight: 23, color: "#5D5852" },
  summaryCard: { marginTop: 22, padding: 18, borderRadius: 20, backgroundColor: "#26211D" },
  summaryTitle: { fontSize: 20, fontWeight: "900", color: "#FFFFFF" },
  summaryText: { marginTop: 8, fontSize: 15, lineHeight: 21, color: "#D9D2C9" },
  summaryGlyph: { marginTop: 12, fontSize: 34, fontWeight: "900", color: "#F2D9A2" },
  sectionTitle: { marginTop: 28, fontSize: 21, fontWeight: "900", color: "#1C1A18" },
  setCard: { marginTop: 12, padding: 17, borderRadius: 19, borderWidth: 1, borderColor: "#E3DBD0", backgroundColor: "#FFFFFF" },
  setHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center" },
  setTitleBlock: { flex: 1, paddingRight: 12 },
  setShortTitle: { fontSize: 25, fontWeight: "900", color: "#9A3D3D" },
  setTitle: { marginTop: 3, fontSize: 18, fontWeight: "900", color: "#1C1A18" },
  setDescription: { marginTop: 8, fontSize: 14, lineHeight: 20, color: "#655E57" },
  setExample: { marginTop: 8, fontSize: 14, fontWeight: "800", color: "#725521" },
  masteryBadge: { minWidth: 54, alignItems: "center", paddingHorizontal: 10, paddingVertical: 8, borderRadius: 14, backgroundColor: "#F0E2DE" },
  masteryValue: { fontSize: 17, fontWeight: "900", color: "#9A3D3D" },
  masteryLabel: { marginTop: 2, fontSize: 10, fontWeight: "800", color: "#7D6E68" },
  progressTrack: { height: 7, marginTop: 14, overflow: "hidden", borderRadius: 99, backgroundColor: "#E9E2D9" },
  progressFill: { height: 7, borderRadius: 99, backgroundColor: "#B54444" },
  setButton: { alignItems: "center", marginTop: 14, paddingVertical: 12, borderRadius: 13, backgroundColor: "#302822" },
  setButtonText: { fontSize: 15, fontWeight: "900", color: "#FFFFFF" },
  mixedCard: { marginTop: 14, padding: 18, borderRadius: 20, borderWidth: 1, borderColor: "#D7C9B8", backgroundColor: "#FFF9ED" },
  mixedTitle: { fontSize: 21, fontWeight: "900", color: "#1C1A18" },
  mixedBody: { marginTop: 8, fontSize: 15, lineHeight: 21, color: "#5D5852" },
  practiceHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginTop: 6 },
  practiceTitle: { flex: 1, paddingRight: 12, fontSize: 24, lineHeight: 30, fontWeight: "900", color: "#1C1A18" },
  counter: { fontSize: 15, fontWeight: "900", color: "#9A3D3D" },
  practiceCard: { marginTop: 20, padding: 20, borderRadius: 22, borderWidth: 1, borderColor: "#DDD4C9", backgroundColor: "#FFFFFF" },
  prompt: { fontSize: 20, lineHeight: 28, fontWeight: "900", color: "#1C1A18" },
  displayText: { marginTop: 18, fontSize: 34, lineHeight: 42, fontWeight: "900", textAlign: "center", color: "#9A3D3D" },
  listenButton: { alignItems: "center", marginTop: 20, paddingVertical: 16, borderRadius: 15, backgroundColor: "#F0E2DE" },
  listenButtonText: { fontSize: 17, fontWeight: "900", color: "#7F3030" },
  input: { marginTop: 20, paddingHorizontal: 16, paddingVertical: 15, borderWidth: 1, borderColor: "#CFC7BC", borderRadius: 14, fontSize: 20, backgroundColor: "#FCFBF8", color: "#1C1A18" },
  choiceButton: { alignItems: "center", marginTop: 10, paddingHorizontal: 12, paddingVertical: 15, borderRadius: 14, borderWidth: 1, borderColor: "#D6CEC3", backgroundColor: "#FCFBF8" },
  choiceButtonSelected: { borderColor: "#B54444", backgroundColor: "#F6E8E5" },
  choiceText: { fontSize: 20, fontWeight: "800", color: "#28231F" },
  submitButton: { alignItems: "center", marginTop: 16, paddingVertical: 15, borderRadius: 14, backgroundColor: "#B54444" },
  submitButtonText: { fontSize: 17, fontWeight: "900", color: "#FFFFFF" },
  disabledButton: { opacity: 0.35 },
  feedback: { marginTop: 16, padding: 15, borderRadius: 14 },
  feedbackCorrect: { backgroundColor: "#E4F2E8" },
  feedbackIncorrect: { backgroundColor: "#F7E2E0" },
  feedbackTitle: { fontSize: 17, fontWeight: "900", color: "#2C2824" },
  feedbackBody: { marginTop: 7, fontSize: 14, lineHeight: 20, color: "#514B45" },
  correctAnswer: { marginTop: 8, fontSize: 16, fontWeight: "900", color: "#7A302D" },
  continueButton: { alignItems: "center", marginTop: 15, paddingVertical: 14, borderRadius: 14, backgroundColor: "#302822" },
  continueButtonText: { fontSize: 16, fontWeight: "900", color: "#FFFFFF" },
  resultContainer: { flex: 1, justifyContent: "center", paddingHorizontal: 24, paddingVertical: 36, backgroundColor: "#F6F3EC" },
  resultEyebrow: { fontSize: 13, fontWeight: "900", letterSpacing: 1.2, textTransform: "uppercase", textAlign: "center", color: "#9A3D3D" },
  resultTitle: { marginTop: 10, fontSize: 34, lineHeight: 40, fontWeight: "900", textAlign: "center", color: "#1C1A18" },
  resultPercent: { marginTop: 18, fontSize: 68, fontWeight: "900", textAlign: "center", color: "#B54444" },
  resultText: { marginTop: 7, fontSize: 16, lineHeight: 22, textAlign: "center", color: "#5D5852" },
  resultButton: { alignItems: "center", marginTop: 20, paddingVertical: 14, borderRadius: 14, backgroundColor: "#B54444" },
  resultSecondaryButton: { alignItems: "center", marginTop: 12, paddingVertical: 14, borderRadius: 14, borderWidth: 1, borderColor: "#CFC7BC", backgroundColor: "#FFFFFF" },
  resultButtonText: { fontSize: 16, fontWeight: "900", color: "#FFFFFF" },
  resultSecondaryText: { fontSize: 16, fontWeight: "900", color: "#38332E" },
  loading: { flex: 1, alignItems: "center", justifyContent: "center", padding: 24 },
  loadingText: { fontSize: 16, fontWeight: "800", color: "#5D5852" },
});
