import type { KanjiStrokeData } from "../domain/kanjiStroke";

// Generated by scripts/generate-kanji-strokes.mjs from KanjiVG.
// The build pipeline replaces this placeholder with the complete N5 dataset.
export const kanjiStrokeDataByLiteral: Readonly<Record<string, KanjiStrokeData>> = {};

export const getKanjiStrokeData = (literal: string): KanjiStrokeData | undefined =>
  kanjiStrokeDataByLiteral[literal];
