import type {
  ExampleSentence,
  Exercise,
  GrammarPoint,
  Lesson,
  VocabularyItem,
} from "../domain/course";
import type { LessonBundle } from "./lessonBundle";

export const lesson007Vocabulary: VocabularyItem[] = [
  {
    id: "word-ichi-number",
    type: "vocabulary",
    writtenForm: "一",
    reading: "いち",
    meaningsRu: ["один"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-ni-number",
    type: "vocabulary",
    writtenForm: "二",
    reading: "に",
    meaningsRu: ["два"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-san-number",
    type: "vocabulary",
    writtenForm: "三",
    reading: "さん",
    meaningsRu: ["три"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-yon-number",
    type: "vocabulary",
    writtenForm: "四",
    reading: "よん",
    alternativeReadings: ["し"],
    meaningsRu: ["четыре"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-go-number",
    type: "vocabulary",
    writtenForm: "五",
    reading: "ご",
    meaningsRu: ["пять"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-roku-number",
    type: "vocabulary",
    writtenForm: "六",
    reading: "ろく",
    meaningsRu: ["шесть"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-nana-number",
    type: "vocabulary",
    writtenForm: "七",
    reading: "なな",
    alternativeReadings: ["しち"],
    meaningsRu: ["семь"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-hachi-number",
    type: "vocabulary",
    writtenForm: "八",
    reading: "はち",
    meaningsRu: ["восемь"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-kyuu-number",
    type: "vocabulary",
    writtenForm: "九",
    reading: "きゅう",
    alternativeReadings: ["く"],
    meaningsRu: ["девять"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-juu-number",
    type: "vocabulary",
    writtenForm: "十",
    reading: "じゅう",
    meaningsRu: ["десять"],
    partOfSpeech: ["числительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-ima",
    type: "vocabulary",
    writtenForm: "今",
    reading: "いま",
    meaningsRu: ["сейчас"],
    partOfSpeech: ["существительное", "наречное употребление"],
    jlptLevel: "N5",
  },
  {
    id: "word-gozen",
    type: "vocabulary",
    writtenForm: "午前",
    reading: "ごぜん",
    meaningsRu: ["до полудня", "AM"],
    partOfSpeech: ["существительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-gogo",
    type: "vocabulary",
    writtenForm: "午後",
    reading: "ごご",
    meaningsRu: ["после полудня", "PM"],
    partOfSpeech: ["существительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-han-time",
    type: "vocabulary",
    writtenForm: "半",
    reading: "はん",
    meaningsRu: ["половина", "половина часа"],
    partOfSpeech: ["существительное", "суффикс"],
    jlptLevel: "N5",
  },
  {
    id: "word-nanji",
    type: "vocabulary",
    writtenForm: "何時",
    reading: "なんじ",
    meaningsRu: ["который час", "во сколько"],
    partOfSpeech: ["вопросительное выражение"],
    jlptLevel: "N5",
  },
];

export const lesson007Grammar: GrammarPoint[] = [
  {
    id: "grammar-clock-hours",
    type: "grammar",
    title: "Часы с ～時",
    meaningRu: "называет время по часам",
    explanationRu:
      "Чтобы назвать час, к числу добавляют 時（じ）. Некоторые сочетания читаются не так, как отдельное число: 四時 — よじ, 七時 — しちじ, 九時 — くじ.",
    formation: ["三時（さんじ）", "四時（よじ）", "七時（しちじ）", "九時（くじ）"],
    cautions: [
      "Для 4 часов говорят よじ, не よんじ и не しじ.",
      "Для 9 часов говорят くじ, не きゅうじ.",
    ],
    jlptLevel: "N5",
  },
  {
    id: "grammar-time-half",
    type: "grammar",
    title: "Половина часа с 半",
    meaningRu: "обозначает тридцать минут после названного часа",
    explanationRu:
      "半（はん） ставится после часа: 七時半 — 7:30. В русском это лучше читать как «семь тридцать», а не переносить буквально выражение «половина восьмого».",
    formation: ["[час] 時 半"],
    jlptLevel: "N5",
  },
  {
    id: "grammar-nanji-question",
    type: "grammar",
    title: "Вопрос 何時ですか",
    meaningRu: "спрашивает текущее время",
    explanationRu:
      "何時（なんじ） означает «который час». Естественный вопрос — 今、何時ですか или 今は何時ですか.",
    formation: ["今、何時ですか", "今は何時ですか"],
    relatedGrammarIds: ["grammar-ka-question"],
    jlptLevel: "N5",
  },
];

export const lesson007Sentences: ExampleSentence[] = [
  {
    id: "sentence-ima-sanji",
    type: "sentence",
    japanese: "今は三時です。",
    reading: "いまはさんじです。",
    translationRu: "Сейчас три часа.",
    grammarIds: ["grammar-wa-topic", "grammar-desu", "grammar-clock-hours"],
    vocabularyIds: ["word-ima", "word-san-number"],
  },
  {
    id: "sentence-gozen-shichiji-han",
    type: "sentence",
    japanese: "午前七時半です。",
    reading: "ごぜんしちじはんです。",
    translationRu: "Сейчас 7:30 утра.",
    grammarIds: ["grammar-desu", "grammar-clock-hours", "grammar-time-half"],
    vocabularyIds: ["word-gozen", "word-nana-number", "word-han-time"],
  },
  {
    id: "sentence-ima-nanji",
    type: "sentence",
    japanese: "今、何時ですか。",
    reading: "いま、なんじですか。",
    translationRu: "Который сейчас час?",
    grammarIds: ["grammar-desu", "grammar-ka-question", "grammar-nanji-question"],
    vocabularyIds: ["word-ima", "word-nanji"],
  },
  {
    id: "sentence-gogo-kuji",
    type: "sentence",
    japanese: "午後九時です。",
    reading: "ごごくじです。",
    translationRu: "Сейчас девять часов вечера.",
    grammarIds: ["grammar-desu", "grammar-clock-hours"],
    vocabularyIds: ["word-gogo", "word-kyuu-number"],
  },
];

export const lesson007Exercises: Exercise[] = [
  {
    id: "exercise-yoji-reading",
    type: "multiple-choice",
    prompt: "Как читается 四時?",
    targetItemIds: ["grammar-clock-hours", "word-yon-number"],
    correctAnswers: ["よじ"],
    distractors: ["よんじ", "しじ", "よじはん"],
    explanationRu: "Четыре часа читается よじ. Это особое чтение, которое нужно запомнить.",
  },
  {
    id: "exercise-shichiji-reading",
    type: "multiple-choice",
    prompt: "Как читается 七時?",
    targetItemIds: ["grammar-clock-hours", "word-nana-number"],
    correctAnswers: ["しちじ"],
    distractors: ["ななじ", "しち", "ななじはん"],
    explanationRu: "При обозначении часа 七時 обычно читается しちじ.",
  },
  {
    id: "exercise-kuji-reading",
    type: "multiple-choice",
    prompt: "Как читается 九時?",
    targetItemIds: ["grammar-clock-hours", "word-kyuu-number"],
    correctAnswers: ["くじ"],
    distractors: ["きゅうじ", "くじゅう", "きゅうじはん"],
    explanationRu: "Девять часов читается くじ, а не きゅうじ.",
  },
  {
    id: "exercise-shichiji-han-choice",
    type: "multiple-choice",
    prompt: "Выбери запись времени 7:30.",
    targetItemIds: ["grammar-clock-hours", "grammar-time-half", "word-han-time"],
    correctAnswers: ["七時半"],
    distractors: ["七時", "八時半", "七半時"],
    explanationRu: "Сначала называется час 七時, затем ставится 半: 七時半.",
  },
  {
    id: "exercise-ima-sanji-input",
    type: "text-input",
    prompt: "Напиши по-японски: Сейчас три часа.",
    targetItemIds: ["grammar-clock-hours", "word-ima", "word-san-number"],
    correctAnswers: ["今は三時です", "今は三時です。"],
    acceptableAnswers: ["今三時です", "今三時です。", "いまはさんじです", "いまはさんじです。"],
    explanationRu: "今 задаёт текущее время, 三時 означает «три часа», предложение заканчивается です.",
  },
  {
    id: "exercise-ima-nanji-input",
    type: "text-input",
    prompt: "Напиши по-японски: Который сейчас час?",
    targetItemIds: ["grammar-nanji-question", "grammar-ka-question", "word-ima", "word-nanji"],
    correctAnswers: ["今何時ですか", "今何時ですか。", "今は何時ですか", "今は何時ですか。"],
    acceptableAnswers: ["いまなんじですか", "いまなんじですか。", "いまはなんじですか", "いまはなんじですか。"],
    explanationRu: "何時 спрашивает час, а か завершает вежливый вопрос.",
  },
  {
    id: "exercise-gogo-hachiji-han-builder",
    type: "sentence-builder",
    prompt: "Собери: Сейчас 20:30.",
    targetItemIds: ["grammar-clock-hours", "grammar-time-half", "word-ima", "word-gogo", "word-hachi-number"],
    correctAnswers: ["今|は|午後|八時|半|です"],
    distractors: ["午前", "九時", "か"],
    explanationRu: "20:30 в двенадцатичасовой системе — 午後八時半.",
  },
  {
    id: "exercise-gogo-kuji-input",
    type: "text-input",
    prompt: "Напиши по-японски: Сейчас девять часов вечера.",
    targetItemIds: ["grammar-clock-hours", "word-gogo", "word-kyuu-number"],
    correctAnswers: ["午後九時です", "午後九時です。", "今は午後九時です", "今は午後九時です。"],
    acceptableAnswers: ["ごごくじです", "ごごくじです。", "いまはごごくじです", "いまはごごくじです。"],
    explanationRu: "午後 показывает время после полудня, а 九時 читается くじ.",
  },
];

export const lesson007: Lesson = {
  id: "lesson-007",
  unitId: "unit-003",
  order: 7,
  title: "Который сейчас час?",
  description: "Часы с ～時, особые чтения, половина часа с 半 и вопрос 何時ですか.",
  theory: lesson007Grammar.map((grammar) => grammar.explanationRu),
  itemIds: [
    ...lesson007Vocabulary.map((item) => item.id),
    ...lesson007Grammar.map((item) => item.id),
    ...lesson007Sentences.map((item) => item.id),
  ],
  exerciseIds: lesson007Exercises.map((exercise) => exercise.id),
  estimatedMinutes: 22,
};

export const lesson007Bundle: LessonBundle = {
  lesson: lesson007,
  vocabulary: lesson007Vocabulary,
  grammar: lesson007Grammar,
  sentences: lesson007Sentences,
  exercises: lesson007Exercises,
  outcomes: [
    "называть полный час",
    "читать 四時／七時／九時 без типичных ошибок",
    "говорить время с половиной часа",
    "спрашивать текущее время",
  ],
};
