import type {
  ExampleSentence,
  Exercise,
  GrammarPoint,
  Lesson,
  VocabularyItem,
} from "../domain/course";
import type { LessonBundle } from "./lessonBundle";

export const lesson006Vocabulary: VocabularyItem[] = [
  {
    id: "word-ie",
    type: "vocabulary",
    writtenForm: "家",
    reading: "いえ",
    meaningsRu: ["дом"],
    partOfSpeech: ["существительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-eki",
    type: "vocabulary",
    writtenForm: "駅",
    reading: "えき",
    meaningsRu: ["станция", "вокзал"],
    partOfSpeech: ["существительное"],
    jlptLevel: "N5",
  },
  {
    id: "word-ikimasu",
    type: "vocabulary",
    writtenForm: "行きます",
    reading: "いきます",
    meaningsRu: ["идти", "ехать"],
    partOfSpeech: ["глагол"],
    jlptLevel: "N5",
  },
  {
    id: "word-benkyoushimasu",
    type: "vocabulary",
    writtenForm: "勉強します",
    reading: "べんきょうします",
    meaningsRu: ["учиться", "заниматься"],
    partOfSpeech: ["глагол"],
    jlptLevel: "N5",
  },
];

export const lesson006Grammar: GrammarPoint[] = [
  {
    id: "grammar-ni-e-destination",
    type: "grammar",
    title: "Направление с に и へ",
    meaningRu: "указывает цель движения",
    explanationRu:
      "После места назначения можно поставить に или へ. に сильнее подчёркивает точку назначения, へ — направление движения.",
    formation: ["[место] に 行きます", "[место] へ 行きます"],
    cautions: ["Частица へ в этой функции произносится え."],
    jlptLevel: "N5",
  },
  {
    id: "grammar-de-action-place",
    type: "grammar",
    title: "Частица で: место действия",
    meaningRu: "показывает, где происходит действие",
    explanationRu:
      "Частица で ставится после места, где кто-то что-то делает: 家で勉強します — «занимаюсь дома».",
    formation: ["[место] で [действие]"],
    cautions: ["に показывает место существования, а で — место активного действия."],
    jlptLevel: "N5",
  },
];

export const lesson006Sentences: ExampleSentence[] = [
  {
    id: "sentence-gakkou-e-ikimasu",
    type: "sentence",
    japanese: "私は学校へ行きます。",
    reading: "わたしはがっこうへいきます。",
    translationRu: "Я иду в школу.",
    grammarIds: ["grammar-wa-topic", "grammar-ni-e-destination", "grammar-masu-polite"],
    vocabularyIds: ["word-watashi", "word-gakkou", "word-ikimasu"],
  },
  {
    id: "sentence-ie-de-benkyou",
    type: "sentence",
    japanese: "私は家で日本語を勉強します。",
    reading: "わたしはいえでにほんごをべんきょうします。",
    translationRu: "Я занимаюсь японским дома.",
    grammarIds: ["grammar-de-action-place", "grammar-o-object", "grammar-masu-polite"],
    vocabularyIds: ["word-watashi", "word-ie", "word-nihongo", "word-benkyoushimasu"],
  },
  {
    id: "sentence-eki-ni-ikimasu",
    type: "sentence",
    japanese: "駅に行きます。",
    reading: "えきにいきます。",
    translationRu: "Иду на станцию.",
    grammarIds: ["grammar-ni-e-destination", "grammar-masu-polite"],
    vocabularyIds: ["word-eki", "word-ikimasu"],
  },
];

const locationConfusions = [
  "grammar-ni-e-destination",
  "grammar-de-action-place",
  "grammar-ni-location",
];

export const lesson006Exercises: Exercise[] = [
  {
    id: "exercise-destination-choice",
    type: "multiple-choice",
    prompt: "Выбери частицу направления: 学校 __ 行きます。",
    targetItemIds: ["grammar-ni-e-destination", "word-gakkou", "word-ikimasu"],
    correctAnswers: ["へ"],
    acceptableAnswers: ["に"],
    distractors: ["で", "を"],
    explanationRu: "С глаголом движения подходят に и へ; здесь основной ответ — へ.",
    variantGroup: "location-particles",
    difficulty: 1,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-action-place-choice",
    type: "multiple-choice",
    prompt: "Выбери частицу места действия: 学校 __ 日本語を勉強します。",
    targetItemIds: [
      "grammar-de-action-place",
      "word-gakkou",
      "word-nihongo",
      "word-benkyoushimasu",
    ],
    correctAnswers: ["で"],
    distractors: ["に", "へ", "が"],
    explanationRu: "Учёба — активное действие, поэтому место отмечается частицей で.",
    variantGroup: "location-particles",
    difficulty: 1,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-existence-place-choice",
    type: "multiple-choice",
    prompt: "Вспомни прошлый урок: 学校 __ 猫がいます。",
    targetItemIds: [
      "grammar-ni-location",
      "grammar-arimasu-imasu",
      "word-gakkou",
      "word-neko",
    ],
    correctAnswers: ["に"],
    distractors: ["で", "へ", "を"],
    explanationRu:
      "Здесь сообщается, где находится кошка. Место существования перед います отмечается に.",
    variantGroup: "location-particles",
    difficulty: 2,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-location-functions-choice",
    type: "multiple-choice",
    prompt: "Какая строка правильно различает три функции места?",
    targetItemIds: locationConfusions,
    correctAnswers: ["に／へ — направление; で — место действия; に — место существования"],
    distractors: [
      "で — направление; に — место действия; へ — место существования",
      "に — только место действия; で — любое местоположение",
      "へ — место действия; で — существование; に — объект действия",
    ],
    explanationRu:
      "Смотри на сказуемое: движение требует に／へ, активное действие — で, существование с あります／います — に.",
    variantGroup: "location-particles",
    difficulty: 2,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-ie-meaning-choice",
    type: "multiple-choice",
    prompt: "Выбери точный перевод: 家で勉強します。",
    targetItemIds: ["grammar-de-action-place", "word-ie", "word-benkyoushimasu"],
    correctAnswers: ["Занимаюсь дома."],
    distractors: ["Иду домой.", "Нахожусь дома.", "Иду заниматься."],
    explanationRu: "Частица で показывает место, где происходит действие 勉強します.",
    variantGroup: "place-action-meaning",
    difficulty: 2,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-eki-listening",
    type: "listening",
    prompt: "Прослушай фразу и выбери её значение.",
    audioText: "駅に行きます。",
    targetItemIds: ["grammar-ni-e-destination", "word-eki", "word-ikimasu"],
    correctAnswers: ["Иду на станцию."],
    distractors: ["Занимаюсь на станции.", "На станции есть человек.", "Иду домой."],
    explanationRu: "駅 — станция, に отмечает цель движения, 行きます — идти или ехать.",
    variantGroup: "destination-listening",
    difficulty: 2,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-eki-builder",
    type: "sentence-builder",
    prompt: "Собери предложение: Иду на станцию.",
    targetItemIds: ["grammar-ni-e-destination", "word-eki", "word-ikimasu"],
    correctAnswers: ["駅|に|行きます", "駅|へ|行きます"],
    distractors: ["へ", "で", "勉強します"],
    explanationRu: "После 駅 можно поставить に или へ, затем используется 行きます.",
    variantGroup: "destination-production",
    difficulty: 2,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-ie-de-builder",
    type: "sentence-builder",
    prompt: "Собери полное предложение: Я занимаюсь японским дома.",
    targetItemIds: [
      "grammar-de-action-place",
      "grammar-o-object",
      "word-ie",
      "word-nihongo",
      "word-benkyoushimasu",
    ],
    correctAnswers: ["私|は|家|で|日本語|を|勉強します"],
    distractors: ["に", "へ", "行きます"],
    explanationRu: "Дом — место действия, поэтому で; японский язык — объект занятия, поэтому を.",
    variantGroup: "place-action-production",
    difficulty: 2,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-two-particles-gap",
    type: "particle-gap",
    prompt: "Вставь две частицы через пробел: 家 __ 日本語 __ 勉強します。",
    targetItemIds: ["grammar-de-action-place", "grammar-o-object"],
    correctAnswers: ["で を"],
    acceptableAnswers: ["でを"],
    explanationRu: "家 — место действия с で, 日本語 — прямой объект занятия с を.",
    variantGroup: "place-action-production",
    difficulty: 3,
    confusionItemIds: ["grammar-ni-e-destination", "grammar-de-action-place", "grammar-o-object"],
  },
  {
    id: "exercise-gakkou-input",
    type: "text-input",
    prompt: "Напиши по-японски: Я иду в школу.",
    targetItemIds: ["grammar-ni-e-destination", "word-gakkou", "word-ikimasu"],
    correctAnswers: [
      "学校に行きます",
      "学校に行きます。",
      "学校へ行きます",
      "学校へ行きます。",
    ],
    acceptableAnswers: [
      "私は学校に行きます",
      "私は学校に行きます。",
      "私は学校へ行きます",
      "私は学校へ行きます。",
      "がっこうにいきます",
      "がっこうへいきます",
      "わたしはがっこうにいきます",
      "わたしはがっこうへいきます",
    ],
    explanationRu: "Цель движения отмечается に или へ. Понятное 私は можно опустить.",
    variantGroup: "destination-production",
    difficulty: 3,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-home-study-input",
    type: "text-input",
    prompt: "Напиши по-японски: Я занимаюсь японским дома.",
    targetItemIds: [
      "grammar-de-action-place",
      "grammar-o-object",
      "word-ie",
      "word-nihongo",
      "word-benkyoushimasu",
    ],
    correctAnswers: [
      "家で日本語を勉強します",
      "家で日本語を勉強します。",
      "私は家で日本語を勉強します",
      "私は家で日本語を勉強します。",
    ],
    acceptableAnswers: [
      "いえでにほんごをべんきょうします",
      "わたしはいえでにほんごをべんきょうします",
    ],
    explanationRu: "Место действия отмечается で, объект занятия 日本語 — частицей を.",
    variantGroup: "place-action-production",
    difficulty: 3,
    confusionItemIds: locationConfusions,
  },
  {
    id: "exercise-correct-ie-ni",
    type: "text-input",
    prompt: "Исправь ошибку: 家に勉強します。",
    targetItemIds: ["grammar-de-action-place", "word-ie", "word-benkyoushimasu"],
    correctAnswers: ["家で勉強します", "家で勉強します。"],
    acceptableAnswers: ["いえでべんきょうします", "いえでべんきょうします。"],
    explanationRu:
      "勉強します — активное действие. Место действия отмечается で: 家で勉強します.",
    variantGroup: "location-particles",
    difficulty: 4,
    confusionItemIds: locationConfusions,
  },
];

export const lesson006: Lesson = {
  id: "lesson-006",
  unitId: "unit-002",
  order: 6,
  title: "Иду в школу",
  description: "Направление движения с に／へ и место действия с частицей で.",
  theory: lesson006Grammar.map((grammar) => grammar.explanationRu),
  itemIds: [
    ...lesson006Vocabulary.map((item) => item.id),
    ...lesson006Grammar.map((item) => item.id),
    ...lesson006Sentences.map((item) => item.id),
  ],
  exerciseIds: lesson006Exercises.map((exercise) => exercise.id),
  estimatedMinutes: 12,
};

export const lesson006Bundle: LessonBundle = {
  lesson: lesson006,
  vocabulary: lesson006Vocabulary,
  grammar: lesson006Grammar,
  sentences: lesson006Sentences,
  exercises: lesson006Exercises,
  outcomes: [
    "указывать направление с に и へ",
    "отмечать место действия частицей で",
    "отличать место действия от места существования",
    "говорить, куда идёшь и где занимаешься",
  ],
};
